ScriptHost:LoadScript("scripts/logic/items.lua")
ScriptHost:LoadScript("scripts/logic/logic.lua")
--ScriptHost:LoadScript("scripts/autotracking.lua")

Tracker:AddItems("items/characters.json")
Tracker:AddItems("items/fears.json")
Tracker:AddItems("items/blackKeys.json")
Tracker:AddItems("items/keyItems.json")
Tracker:AddItems("items/questItems.json")
Tracker:AddItems("items/hostedItems.json")

Tracker:AddMaps("maps/maps.json")

Tracker:AddLayouts("layouts/display/tracker.json")
Tracker:AddLayouts("layouts/itemGrids/character_grid.json")
Tracker:AddLayouts("layouts/itemGrids/fears_grid.json")
Tracker:AddLayouts("layouts/itemGrids/blackKeys_grid.json")
Tracker:AddLayouts("layouts/itemGrids/hangman_grid.json")
Tracker:AddLayouts("layouts/itemGrids/keyItems_grid.json")
Tracker:AddLayouts("layouts/itemGrids/questItems_grid.json")

Tracker:AddLocations("locations/vast_forest/VF_North.json")
Tracker:AddLocations("locations/vast_forest/VF_South.json")
Tracker:AddLocations("locations/otherworld/otherworld.json")
Tracker:AddLocations("locations/otherworld/junkyard.json")
Tracker:AddLocations("locations/pyrefly_forest/pyrefly_forest.json")
Tracker:AddLocations("locations/pyrefly_forest/sm_village.json")
Tracker:AddLocations("locations/pyrefly_forest/dungeon.json")
Tracker:AddLocations("locations/pyrefly_forest/castle.json")
Tracker:AddLocations("locations/deepwell/resort.json")
Tracker:AddLocations("locations/deepwell/highway.json")
Tracker:AddLocations("locations/deeperwell/trench.json")
Tracker:AddLocations("locations/deeperwell/humphrey.json")
Tracker:AddLocations("locations/oasis/oasis.json")
Tracker:AddLocations("locations/snowglobe/snowglobe.json")
Tracker:AddLocations("locations/abyss/abyss.json")